export const config = {
  LOGIN_LENGTH: 10,
  PASSWORD_MIN_LENGTH: 4,
  SERVER_URL: 'https://message-system.site/',
  NUMBER_OF_FETCHED_MESSAGES: 5,
  NUMBER_OF_FETCHED_THREADS: 100,
  MAX_FILE_SIZE: 1024 * 1024 * 4,
  MAX_NUMBER_OF_ATTACHMENTS: 5,
};
